{
 "title": "Credit Used by Companies with Pages",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(credit.credit_used) AS total_credit_used\nFROM\n  app_usage_log credit\nWHERE\ncredit.method_used IN ('FELLOW_KV2', 'AI') and\n  $__timeFilter(credit.created_on);"
    }
   ]
  },
  {
   "title": "PI Chart",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  org.name AS organisation_name,\n  SUM(credit.credit_used) AS total_credit_used\nFROM\n  app_usage_log credit\nJOIN\n  organisations org ON credit.org_id = org.id\nWHERE\n  $__timeFilter(credit.created_on)\nGROUP BY\n  org.name\nORDER BY\n  total_credit_used DESC;"
    }
   ]
  },
  {
   "title": "Pages Only",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 14, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    org.name AS organisation_name,\n    DATE_TRUNC('month', credit.created_on) AS month,\n    SUM(credit.credit_used) AS total_credit_used\nFROM\n    app_usage_log credit\nJOIN\n    organisations org ON credit.org_id = org.id\nWHERE\n    credit.method_used IN ('FELLOW_KV2', 'AI')\n    AND $__timeFilter(credit.created_on)\nGROUP BY\n    org.name,\n    DATE_TRUNC('month', credit.created_on)\nORDER BY\n    month ASC,\n    organisation_name ASC;"
    }
   ]
  }
 ]
}