{
 "title": "DocBits Usage Overview",
 "tags": [ "TV" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avrg. Document Process Time",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH doc_sum AS (\n    SELECT\n        doc.id AS document_id,\n        doc.org_id,\n        SUM((json_pairs.value)::numeric) AS sum_time_per_doc\n    FROM\n        documents AS doc\n        CROSS JOIN LATERAL jsonb_each_text(doc.extracted_data -> 'time_logs') AS json_pairs\n    WHERE\n        doc.is_deleted = false\n        AND doc.created_on >= $__timeFrom() AND doc.created_on <= $__timeTo()\n    GROUP BY\n        doc.id,\n        doc.org_id\n)\nSELECT\n    org_cache.name AS organisation_name,\n    AVG(doc_sum.sum_time_per_doc) AS avg_time_per_document\nFROM\n    doc_sum\n    JOIN organisation_cache AS org_cache ON doc_sum.org_id = org_cache.id\nGROUP BY\n    org_cache.name\nORDER BY\n    avg_time_per_document DESC;"
    }
   ]
  },
  {
   "title": "Document Pages per Hour",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    o.name AS organisation_name,\n    AVG(hu.hourly_credit_used) AS average_credit_used_per_hour\nFROM (\n    SELECT\n        org_id,\n        DATE_TRUNC('hour', credit.created_on) AS hour,\n        SUM(credit.credit_used) AS hourly_credit_used\n    FROM\n        app_usage_log credit\n    WHERE\n        credit.method_used IN ('FELLOW_KV2', 'AI')\n        AND $__timeFilter(credit.created_on)\n    GROUP BY\n        org_id,\n        DATE_TRUNC('hour', credit.created_on)\n) AS hu\nJOIN\n    organisations o ON hu.org_id = o.id\nGROUP BY\n    o.name\nORDER BY\n    o.name ASC;"
    }
   ]
  },
  {
   "title": "Red Markers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n org_cache.name AS organisation_name,\n count(*) as Red_Markers\nFROM\n documents AS doc\nJOIN\n organisation_cache AS org_cache ON doc.org_id = org_cache.id\nWHERE\n doc.is_deleted = false\n AND doc.restart_allowed = true\n AND doc.created_on >= $__timeFrom() AND doc.created_on <= $__timeTo()\nGROUP BY\n org_cache.name\nORDER BY\n Red_Markers DESC;"
    }
   ]
  },
  {
   "title": "Pending Watchdawg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n org_cache.name AS organisation_name,\n count(*) as Red_Markers\nFROM\n documents AS doc\nJOIN\n organisation_cache AS org_cache ON doc.org_id = org_cache.id\nWHERE\n doc.is_deleted = false\nAND\n doc.status = 'pending_watcher_export'\nAND\n doc.created_on >= $__timeFrom() AND doc.created_on <= $__timeTo()\nGROUP BY\n org_cache.name\nORDER BY\n Red_Markers DESC;"
    }
   ]
  }
 ]
}