{
 "title": "DocBits",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "prod, demo, sandbox, dev" }
  ]
 },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(nginx_ingress_controller_requests{status=~\"5[0-9][0-9]\"}[1d])) / sum(rate(nginx_ingress_controller_requests[1d])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress 2XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m]))",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "Request Duration Histogram (3m)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[3m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Logs (All Namespaces)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"ingress-nginx\",app=\"ingress-nginx\",container=\"controller\"}[3m]))"
    }
   ]
  },
  {
   "title": "Ingress 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"502\"}[1m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"503\"}[1m]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"499\"}[5m]))",
     "legendFormat": "499"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections[5m]))",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum[3m])) * 10",
     "legendFormat": "AVG"
    },
    {
     "expr": "max(rate(nginx_ingress_controller_request_duration_seconds_sum[3m]))",
     "legendFormat": "MAX"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[3m])) by (le)) * 10",
     "legendFormat": "Histogram"
    },
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum[3m])) / avg(rate(nginx_ingress_controller_request_duration_seconds_count[3m]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "max(rate(nginx_ingress_controller_request_duration_seconds_sum[3m])) / max(rate(nginx_ingress_controller_request_duration_seconds_count[3m]))",
     "legendFormat": "MAX"
    },
    { "expr": "2", "legendFormat": "__auto" },
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Latency by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(increase(nginx_ingress_controller_request_duration_seconds_sum[3m])) by (host) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m])) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"502\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"503\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"499\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"app\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 146 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"app\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 146 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"app\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"app\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"app-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"app-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"app\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "APP Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"app\",container=\"app\"}[3m]))"
      }
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"api\", namespace=\"$namespace\"}[3m])) * 1000",
     "legendFormat": "vCore"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"api\", namespace=\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"api\", namespace=\"$namespace\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(response_total{deployment=\"api\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"api-.*-.*$\"}[3m]))",
     "legendFormat": "Send"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"api-.*-.*$\"}[3m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"api\", namespace=\"$namespace\"}[3m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"$namespace\",app=\"api\",container=\"api\"}[3m]))"
    }
   ]
  },
  { "title": "API Celery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"api-celery\", namespace=\"$namespace\"}[3m])) * 1000",
     "legendFormat": "vCore"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"api-celery\", namespace=\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"api-celery\", namespace=\"$namespace\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(response_total{deployment=\"api-celery\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"api-celery-.*\"}[3m]))",
     "legendFormat": "Send"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"api-celery-.*\"}[3m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"api-celery\", namespace=\"$namespace\"}[3m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"$namespace\", app=\"api-celery\", container=\"api-celery\"}[3m]))"
    }
   ]
  },
  {
   "title": "Queues Length",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "redis_key_size{db=\"db5\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "API Flower", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"api-flower\", namespace=\"$namespace\"}[3m])) * 1000",
     "legendFormat": "vCore"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"api-flower\", namespace=\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"api-flower\", namespace=\"$namespace\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate(response_total{deployment=\"api-flower\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"api-flower-.*\"}[3m]))",
     "legendFormat": "Send"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"api-flower-.*\"}[3m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"api-flower\", namespace=\"$namespace\"}[3m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"$namespace\",app=\"api-flower\",container=\"api-flower\"}[3m]))"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"auth\", namespace=\"$namespace\"}[3m])) * 1000",
     "legendFormat": "vCore"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 89 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"auth\", namespace=\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"auth\", namespace=\"$namespace\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate(response_total{deployment=\"auth\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"auth-.*\"}[3m]))",
     "legendFormat": "Send"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"auth-.*\"}[3m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"auth\", namespace=\"$namespace\"}[3m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"$namespace\",app=\"auth\",container=\"auth\"}[3m]))"
    }
   ]
  },
  {
   "title": "Cloud Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"cloudintegration\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"cloudintegration\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 151 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"cloudintegration\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 159 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"cloudintegration\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 159 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"cloudintegration-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"cloudintegration-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 159 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"cloudintegration\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 159 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"cloudintegration\",container=\"cloudintegration\"}[3m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "fellowkv",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"fellowkv\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"fellowkv\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"fellowkv\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 160 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"fellowkv\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 160 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"fellowkv-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"fellowkv-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 160 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"fellowkv\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 160 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"fellowkv\",container=\"fellowkv\"}[3m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Landing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"landing\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 153 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"landing\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 153 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"landing\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"landing\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 161 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"landing-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"landing-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 161 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"landing\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 161 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"landing\",container=\"landing\"}[3m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "OCR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"ocr\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 146 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"ocr\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 146 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"ocr\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"ocr\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"ocr-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"ocr-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"ocr\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "APP Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 154 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"ocr\",container=\"ocr\"}[3m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "XRechnung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"xrechnung\", namespace=\"$namespace\"}[3m])) * 1000",
       "legendFormat": "vCore"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 147 },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"xrechnung\", namespace=\"$namespace\"}) / 1024 / 1024",
       "legendFormat": "GB"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 147 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{deployment=\"xrechnung\", namespace=\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "sum(rate(response_total{deployment=\"xrechnung\", namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 155 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"xrechnung-.*\"}[3m]))",
       "legendFormat": "Send"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"xrechnung-.*\"}[3m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"xrechnung\", namespace=\"$namespace\"}[3m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 155 },
     "targets": [
      {
       "expr": "sum(rate({namespace=\"$namespace\",app=\"xrechnung\",container=\"xrechnung\"}[3m]))"
      }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(redis_cpu_user_seconds_total[3m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(redis_cpu_sys_seconds_total[3m]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes / 1024 / 1024)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(redis_memory_max_bytes / 1024 / 1024)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Network (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total[3m]) / 1024 / 1024)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total[3m]) / 1024 / 1024)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(rate(redis_keyspace_hits_total[3m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(redis_keyspace_misses_total[3m]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "targets": [
    {
     "expr": "sum(rate(redis_latency_percentiles_usec_sum[3m])) / 60 / 60 / 60",
     "legendFormat": "Percentile"
    },
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total[3m]))",
     "legendFormat": "Command Duration"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "targets": [
    { "expr": "sum(redis_connected_clients)", "legendFormat": "Connected Clients" },
    { "expr": "sum(redis_blocked_clients)", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Keys by DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "targets": [
    { "expr": "sum(redis_db_keys) by (db)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total[3m]))",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total[3m]))",
     "legendFormat": "Evicted"
    },
    { "expr": "sum(redis_db_keys)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "targets": [
    {
     "expr": "sum(rate(redis_errors_total[3m])) by (err)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(redis_errors_total[3m]))",
     "legendFormat": "Sum"
    }
   ]
  }
 ]
}