{
 "title": "PostgreSQL Infrastructure",
 "description": "A basic dashboard for monitoring PostgreSQL database clusters using collectd v5+, TimescaleDB/PostgreSQL v10+ and Grafana v6+",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SELECT DISTINCT ON (host) host as host from identifiers;"
   },
   {
    "name": "database",
    "query": "SELECT DISTINCT ON (plugin_inst) plugin_inst as plugin_inst from identifiers where plugin = 'postgresql' and host = '$host';"
   }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU activity (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  type_inst AS metric,\n  last(value,tstamp) AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'cpu' AND\n  type = 'percent' AND\n  type_inst != 'idle' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1, type_inst,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  name AS metric,\n  last(value,tstamp) AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'load' AND\n  value = value AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  'TX: ' || plugin_inst  AS metric,\n  (CASE WHEN avg(value) >= lag(avg(value)) OVER (PARTITION BY 'TX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) THEN avg(value) - lag(avg(value)) OVER (PARTITION BY 'TX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) WHEN lag(avg(value)) OVER (PARTITION BY 'TX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) IS NULL THEN NULL ELSE avg(value) END)/extract(epoch from min(tstamp) - lag(min(tstamp)) OVER (PARTITION BY 'TX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval))) AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'interface' AND\n  type = 'if_octets' AND\n  name = '''tx''' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1, plugin_inst, type,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  'RX: ' || plugin_inst  AS metric,\n  (CASE WHEN avg(value) >= lag(avg(value)) OVER (PARTITION BY 'RX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) THEN avg(value) - lag(avg(value)) OVER (PARTITION BY 'RX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) WHEN lag(avg(value)) OVER (PARTITION BY 'RX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) IS NULL THEN NULL ELSE avg(value) END)/extract(epoch from min(tstamp) - lag(min(tstamp)) OVER (PARTITION BY 'RX: ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval))) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin = 'interface' AND\n  type = 'if_octets' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo() AND\n  tstamp < $__timeTo()\nGROUP BY 1, plugin_inst, type,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  'read - ' || plugin_inst  AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY 'read - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY 'read - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) WHEN lag(last(value,tstamp)) OVER (PARTITION BY 'read - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) IS NULL THEN NULL ELSE last(value,tstamp) END) / 60 AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'disk' AND\n  type = 'disk_octets' AND\n  name = '''read''' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1, plugin_inst, type,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  'write - ' || plugin_inst  AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY 'write - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY 'write - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) WHEN lag(last(value,tstamp)) OVER (PARTITION BY 'write - ' || plugin_inst  ORDER BY $__timeGroup(tstamp,$__interval)) IS NULL THEN NULL ELSE last(value,tstamp) END) / 60 AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'disk' AND\n  type = 'disk_octets' AND\n  name = '''write''' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1, plugin_inst, type,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Space: Used",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  DISTINCT ON (REPLACE('/' || plugin_inst,'-', '/'))\n REPLACE('/' || plugin_inst,'-', '/') as mountpoint, value\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'df' AND\n  type = 'df_complex' AND \n  type_inst = 'used' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nORDER BY 1,2 DESC"
    }
   ]
  },
  {
   "title": "Disk Space: Used %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  DISTINCT ON (REPLACE('/' || plugin_inst,'-', '/'))\n REPLACE('/' || plugin_inst,'-', '/') as mountpoint, value\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'df' AND\n  type = 'percent_bytes' AND \n  type_inst = 'used' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nORDER BY 1,2 DESC"
    }
   ]
  },
  {
   "title": "Disk Space: Free",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  DISTINCT ON (REPLACE('/' || plugin_inst,'-', '/'))\n REPLACE('/' || plugin_inst,'-', '/') as mountpoint, value\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'df' AND\n  type = 'df_complex' AND \n  type_inst = 'free' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nORDER BY 1,2 DESC"
    }
   ]
  },
  {
   "title": "Disk Space: % Change over 24h",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,24h),\n  REPLACE('/' || plugin_inst,'-', '/') AS metric,\n  (CASE WHEN avg(value) >= lag(avg(value)) OVER (PARTITION BY REPLACE('/' || plugin_inst,'-', '/') ORDER BY $__timeGroup(tstamp,24h)) THEN avg(value) - lag(avg(value)) OVER (PARTITION BY REPLACE('/' || plugin_inst,'-', '/') ORDER BY $__timeGroup(tstamp,24h)) WHEN lag(avg(value)) OVER (PARTITION BY REPLACE('/' || plugin_inst,'-', '/') ORDER BY $__timeGroup(tstamp,24h)) IS NULL THEN NULL ELSE avg(value) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo() AND\n  host = '$host' AND\n  plugin = 'df' AND\n  type = 'df_complex' AND\n  type_inst = 'used' AND\n  value IS NOT NULL\nGROUP BY 1, REPLACE('/' || plugin_inst,'-', '/'),2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  type_inst AS metric,\n  last(value,tstamp) AS \"value\"\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin = 'memory' AND\n  type = 'memory' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1, plugin_inst, type,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "PostgreSQL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  avg(value) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  type = 'pg_numbackends_n' AND\n  plugin = 'postgresql' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Commit/Rollback",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END)/extract(epoch from min(tstamp) - lag(min(tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp)) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_xact' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  type AS metric,\n  last(value,tstamp) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_db_size' AND\n  tstamp > $__timeFrom() AND\n  tstamp <  $__timeTo()\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "xacts since last vacuum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  type AS metric,\n  last(value,tstamp) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_db_vac_age' AND\n  tstamp > $__timeFrom() AND\n  tstamp <  $__timeTo()\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  DISTINCT ON (type_inst)\n  type_inst as table, value\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'table_sizes' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nORDER BY 1,2 DESC"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  DISTINCT ON (type_inst)\n  type_inst as table, value\nFROM collectd\nWHERE\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  name = '''indexes_size''' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY 1,2\nORDER BY 1,2 DESC"
    }
   ]
  },
  {
   "title": "Row Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_scan' AND\n  type_inst = 'idx_tup_fetch' AND\n  tstamp > $__timeFrom() AND\n  tstamp <  $__timeTo()\nGROUP BY type_inst, tstamp, type_inst,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_blks' AND\n  type_inst = 'idx_read' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp, type_inst,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_n_tup_c' AND\n  type_inst = 'ins' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp, type_inst,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_n_tup_c' AND\n  type_inst = 'upd' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp, type_inst,2\nORDER BY 1,2"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  type_inst AS metric,\n  (CASE WHEN last(value,tstamp) >= lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) THEN last(value,tstamp) - lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) WHEN lag(last(value,tstamp)) OVER (PARTITION BY type_inst ORDER BY tstamp) IS NULL THEN NULL ELSE last(value,tstamp) END) AS \"value\"\nFROM collectd\nWHERE\n  $__timeFilter(tstamp) AND\n  host = '$host' AND\n  plugin_inst = '$database' AND\n  plugin = 'postgresql' AND\n  type = 'pg_n_tup_c' AND\n  type_inst = 'del' AND\n  tstamp > $__timeFrom() AND\n  tstamp < $__timeTo()\nGROUP BY type_inst, tstamp, type_inst,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}