{
 "title": "Polydocs-Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "dev,stage,sandbox,prod" }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/kubepods/besteffort/pod.*\"}) / sum (machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"/kubepods/besteffort/pod.*\"}[1m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs\"}) - sum(node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs\"})) \n/ sum(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/kubepods/besteffort/pod.*\",kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"/kubepods/besteffort/pod.*\",kubernetes_io_hostname=~\"^.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs\"}) - sum(node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs\"})\n"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\"}[1m])) by (pod_name, pod)",
     "legendFormat": "-> {{ pod_name }}{{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\"}[1m])) by (pod_name, pod)",
     "legendFormat": "<- {{ pod_name }}{{ pod }}"
    }
   ]
  },
  { "title": "$namespace data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "namespace" },
  {
   "title": "CPU Usage of NodePool $namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=~\".*\"}[1m])) by (container) / sum(machine_cpu_cores{kubernetes_io_hostname=~\".*\"}) * 100",
     "legendFormat": "namespace cpu usage"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$namespace.*\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$namespace.*\"}) * 100",
     "legendFormat": "nodepool cpu usage"
    }
   ]
  },
  {
   "title": "Memory Usage of NodePool $namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\"}) by (container) / sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$namespace.*\"}) * 100",
     "legendFormat": "namespace memory usage"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$namespace.*\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$namespace.*\"}) * 100",
     "legendFormat": "nodepool memory usage"
    }
   ]
  },
  {
   "title": "Used by namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"/kubepods/besteffort/pod.*\",kubernetes_io_hostname=~\"^.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*\"})"
    }
   ]
  },
  {
   "title": "Used by namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/kubepods/besteffort/pod.*\",kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Memory Usage for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Namespace $namespace memory usage"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage of $namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "namespace $namespace cpu usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (container)",
     "legendFormat": "{{ container }} "
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"^$namespace\"}[1m])) by (pod_name, pod)",
     "legendFormat": "-> {{ pod_name }}{{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$namespace\"}[1m])) by (pod_name, pod)",
     "legendFormat": "<- {{ pod_name }}{{ pod }}"
    }
   ]
  },
  { "title": "alerts dev", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory Usage dev",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"dev\"})",
     "legendFormat": "Namespace $namespace memory usage"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"dev\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage of dev",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"dev\"}[1m])) by (container)",
     "legendFormat": "{{ container }} "
    }
   ]
  },
  {
   "title": "dev deployments available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"dev\"}) by (deployment) / sum(kube_deployment_status_replicas{namespace=\"dev\"}) by (deployment) * 100",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "DEV cpu throttle",
   "type": "timeseries",
   "description": "Time of pods being throttled by k8s",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"dev\"}[1m])) by (container)",
     "legendFormat": "throttled seconds - {{ container }}"
    }
   ]
  },
  {
   "title": "Dev Memory usage / Memory limit ",
   "type": "timeseries",
   "description": "The percentage of used memory in prospect of the memory limit granted",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"dev\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"dev\"}) by (container) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "alerts stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "stage deployments available",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=\"stage\"}) by (deployment) / sum(kube_deployment_status_replicas{namespace=\"stage\"}) by (deployment) * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "CPU Usage of stage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"stage\"}[1m])) by (container)",
       "legendFormat": "{{ container }} "
      }
     ]
    },
    {
     "title": "Memory Usage stage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"stage\"})",
       "legendFormat": "Namespace $namespace memory usage"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"stage\"}) by (container)",
       "legendFormat": "{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}